# Generated by Django 5.1.5 on 2025-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
