# Generated by Django 5.1.5 on 2025-02-01 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2013)], verbose_name='Year')),
                ('page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='MonthCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, verbose_name='Month')),
                ('background_image', models.ImageField(upload_to='month_calendars/', verbose_name='Background image')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Activity title')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('custom_date', models.CharField(blank=True, max_length=280, null=True, verbose_name='Custom date')),
                ('hour_start', models.TimeField(blank=True, null=True, verbose_name='Hour')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='calendars.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.monthcalendar'),
        ),
    ]
