# Generated by Django 5.1.5 on 2026-02-21 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2013)], verbose_name='Year'),
        ),
    ]
