# Generated by Django 5.1.5 on 2026-02-21 03:45

import credentials.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the user whose credentials are being created.', max_length=240, verbose_name='Wikimedia username')),
                ('full_name', credentials.fields.EncryptedTextField(help_text='Full name of user.', max_length=240, verbose_name='Full name')),
                ('cpf', credentials.fields.EncryptedTextField(blank=True, help_text='CPF of user.', null=True, verbose_name='CPF')),
                ('cin', credentials.fields.EncryptedTextField(blank=True, help_text='CIN of user.', max_length=24, null=True, verbose_name='CIN')),
                ('photograph', credentials.fields.EncryptedTextField(blank=True, default='', help_text='Photograph filename.', max_length=420, verbose_name='Photograph filename')),
                ('url', models.URLField(blank=True, default='', help_text='Meta-Wiki Profile URL.', verbose_name='Meta-Wiki Profile URL')),
                ('event', models.CharField(help_text='Event which credentials are being created.', max_length=240, verbose_name='Event name')),
                ('verification_code', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Verification code')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued at')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_issued_by', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
            ],
        ),
    ]
