# Generated by Django 5.1.5 on 2026-02-23 08:07

import credentials.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='photograph',
            field=credentials.fields.EncryptedTextField(default='', help_text='Photograph URL.', max_length=420, verbose_name='Photograph URL'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='valid_from',
            field=models.DateField(default='2026-01-01', verbose_name='Valid from'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='valid_until',
            field=models.DateField(default='2026-12-31', verbose_name='Valid until'),
            preserve_default=False,
        ),
    ]
