# Generated by Django 5.1.5 on 2025-02-01 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pronoun', models.CharField(choices=[('a', 'a'), ('o', 'o')], default='o', max_length=200)),
                ('hours', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d+[h,H]\\d+$')])),
                ('role', models.CharField(default='ouvinte', max_length=200)),
                ('background', models.ImageField(upload_to='backgrounds/')),
                ('certificate_hash', models.CharField(blank=True, max_length=500, null=True)),
                ('emitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
