# Generated by Django 5.1.5 on 2025-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='with_hours',
            field=models.BooleanField(default=True),
        ),
    ]
